######################################################################
# Automatically generated by qmake (2.01a) So. Okt 21 07:44:17 2012
######################################################################

TEMPLATE = app
TARGET = Interlace
DEPENDPATH += .
INCLUDEPATH += . /usr/local/include
LIBS += /usr/local/lib -lexiv2

DESTDIR = ../bin

# Input
HEADERS += Interlace.h
SOURCES += Interlace.cpp
